import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Layout/Header";
import { Overheader } from "./components/Layout/Overheader";
import { Footer } from "./components/Layout/Footer";
import { ScrollToTopButton } from "./components/Layout/ScrollToTopButton";
import AuthProvider from "@/context/AuthProvider";
import { ProductProvider } from "@/context/ProductProvider";
import { FavoritesProvider } from "@/context/FavoritesContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#166534" },
    { media: "(prefers-color-scheme: dark)", color: "#166534" },
  ],
};

export const metadata: Metadata = {
  title: "AgroPeti - Produse agricole de calitate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ProductProvider>
            <FavoritesProvider>
              <Overheader />
              <Header />
              <main>{children}</main>
              <Footer />
              <ScrollToTopButton />
            </FavoritesProvider>
          </ProductProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
